services:
  gateway:
    image: thaihoangnhantk/gateway-svc:latest
    ports:
      - "8080:8080"
    environment:
      - ClientApp=http://localhost:3000
      - IdentityServerUrl=http://identity-service:8080
      - ReverseProxy__Clusters__identity__Destinations__identityApi__Address=http://identity-service:8080/

  identity-service:
    image: thaihoangnhantk/identity-svc:latest
    ports:
      - "5003:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=ep-flat-frost-aogh49jw-pooler.c-2.ap-southeast-1.aws.neon.tech;Database=identity;Username=neondb_owner;Password=npg_XP1nItYZu0kw;SSL Mode=Require;Trust Server Certificate=true