services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=products
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
      # - /var/lib/postgresql
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672 
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # UI
    restart: unless-stopped
  # product-svc:
  #   image: thaihoangnhantk/product-svc:latest
  #   build:
  #     context: .
  #     dockerfile: server/ProductService
volumes:
  pgdata:
  mongodata: