<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Infrastructure.EF\Infrastructure.EF.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Shared.Core.EF\Shared.Core.EF.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Shared.Web\Shared.Web.csproj" />
    <ProjectReference Include="..\Contract\Contract.csproj" />
  </ItemGroup>

</Project>
