syntax = "proto3";
import "google/protobuf/empty.proto";

option csharp_namespace = "IdentityService.Grpc";

service GrpcIdentity {
    rpc GetUsersByIds (GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
    rpc GetAllUsers (google.protobuf.Empty) returns (GetAllUsersResponse);
}

message GetUsersByIdsRequest {
    repeated string userIds = 1;
}

message GetUsersByIdsResponse {
    repeated UserInfo users = 1;
}

message GetAllUsersResponse {
    repeated UserInfo users = 1;
}

message UserInfo {
    string userId = 1;
    string userName = 2;
    string imageUrl = 3;
    optional bool isAdmin = 4;
}